# .github/workflows/update-sitemap.yaml

name: update-sitemap

on:
  schedule:
    - cron: '0 15 * * *'

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Ping to Google
        run: |
          curl -X GET "http://www.google.com/ping?sitemap=https://oziidi.github.io/sitemap.xml"
          curl -X GET "http://www.google.com/ping?sitemap=https://oziidi.github.io/rss/feed.xml"
          curl -X GET "http://www.google.com/ping?sitemap=https://oziidi.github.io/rss/atom.xml"
